### PR TITLE
remove all dialyzer warning

### LINKED ISSUE #28: issue with dialyzer on elixir
Example to  reproduce the issue with dialyzer:
[pfcpdialyzer.tar.gz](https://github.com/travelping/pfcplib/files/7511095/pfcpdialyzer.tar.gz)

When I call the :pfcp_packet.decode dialyzer believes that an exception will always be lifted by module pfcp_packet
with gtp_packet I don't have this behaviour

To verify that test is working correctly:
- mix deps.get
- iex -S mix
- Pfcpdialyzer.test()

to see the dialyzer error 
mix dialyzer
lib/pfcpdialyzer.ex:42:unused_fun
Function dump_pfcp_data/1 will never be called.
________________________________________________________________________________

### PR DESCRIPTION
**Pull request by jbdamiano**
Closes #28

### CODE REVIEW

**Review by vkatsuba — COMMENTED** [review]
Thanks for PR. Could you please:
* Change all `'undefined'` to `undefined`
* Add call of `dialyzer` in https://github.com/travelping/pfcplib/blob/master/.github/workflows/main.yml#L31
and check if this works in https://github.com/jbdamiano/pfcplib/actions?

**Comment by vkatsuba** [comment]
LGTM. @jbdamiano please squash all commits in this PR into single commit?

**Comment by jbdamiano** [comment]
done github action was ok except for slack step but as I don't have the slack configuration, it's ok.

**Comment by jbdamiano** [comment]
@vkatsuba I changed the dependencies in the issue's example  to retrieve my cloned repository.

the problem is fixed.

**Review by vkatsuba — APPROVED** [review]
LGTM.

**Pull request merged**
